OPTIONS(ERRORS=10000, bindsize=512000, rows=10000)
LOAD DATA
CHARACTERSET WE8ISO8859P1
INTO TABLE PROXY_CNTL_NUMBER_DF
FIELDS TERMINATED BY  '%~|'
TRAILING NULLCOLS
( 
	CNTL_NBR_KEY ,      
	JOB_NBR,
	MONEY_MGR_NO,            
	PIN,                
	CLNT_PIN_REQD,
	EDELIVERY_FLAG,     
	HOUSHOLDING_FLAG,   
	VOTE_INSTRUCTION,   
)